export interface TechnicianReview {
  id: string;
  customerName: string;
  area: string;
  rating: number;
  date: string;
  comment: string;
  verifiedJob: boolean;
  serviceType: string;
}

export interface TechnicianCertification {
  title: string;
  issuer: string;
  year: string;
  verified: boolean;
  credentialId?: string;
}

export interface TechnicianSkill {
  name: string;
  proficiency: number; // 0 to 100
  experienceYears: number;
}

export interface Technician {
  id: string;
  name: string;
  title: string; // e.g. "Lead Electrical Engineer", "Certified Solar & Inverter Specialist"
  badgeId: string; // e.g. "BN-ELEC-2024-042"
  experienceYears: number;
  primarySector: string; // e.g. "Residential & Commercial Power Systems"
  subSectors: string[];
  photo: string;
  rating: number;
  reviewsCount: number;
  completedJobs: number;
  verificationStatus: 'verified' | 'certified' | 'master';
  licenseNumber: string; // e.g. "WB-CEI-LIC-74892"
  issuingAuthority: string; // e.g. "Govt. of West Bengal - Electrical Licensing Board"
  status: 'available' | 'on_duty' | 'busy';
  statusText?: string;
  phone: string;
  email: string;
  whatsapp?: string;
  emergencySupport: boolean;
  serviceAreas: string[];
  workingHours: string; // e.g. "8:00 AM - 8:00 PM"
  startingRate: number; // in INR
  rateUnit: string; // e.g. "per visit / consultation"
  about: string;
  aiDescription?: string; // Short 1-2 sentence AI description generated by Gemini
  certifications: TechnicianCertification[];
  skills: TechnicianSkill[];
  toolsCarried: string[];
  recentReviews: TechnicianReview[];
  featured?: boolean;
  joinedDate?: string;
}
